### ISSUE TITLE
proper credit on README

### ISSUE THREAD

**Issue by pmerson** [saantiaguilera/feature-flags#6]
Hi Santi, great work on this lib. 
This (minor) issue is just to point out that the author of the Feature Toggles article you reference twice in README is **not** Martin Fowler. The author is **Pete Hodgson**. It just turns out the article is hosted on martinfowler.com.

**Comment by saantiaguilera** [comment]
Nice find! So sorry for the mislead, changing it right now. Thanks for the heads up :)
